<?php
use Mageserv\Yamm\Block\Adminhtml\System\Config\Sync;
use Mageserv\Yamm\Helper\Data;

/** @var Sync $block */
?>
<div class="actions actions-test-email" id="<?= /* @noEscape */ $block->getElementId() ?>">
    <div id="yamm-sync">
        <div id="progress-content" class="progress-content" style="display: none">
            <p class="text-right">
                <span id="syncing" class="syncing"><?= $block->escapeHtml(__('Syncing...')) ?></span>
                <span id="sync-percent">0%</span>
            </p>
            <div class="progress">
                <div class="progress-bar">
                </div>
            </div>
        </div>
        <div id="progress-content-<?= \Mageserv\Yamm\Model\Config\Source\CronType::CUSTOMER;?>" class="progress-content" style="display: none">
            <p class="text-right">
                <span id="syncing-<?= \Mageserv\Yamm\Model\Config\Source\CronType::CUSTOMER;?>" class="syncing"><?= $block->escapeHtml(__('Syncing Customers...')) ?></span>
                <span id="sync-percent-<?= \Mageserv\Yamm\Model\Config\Source\CronType::CUSTOMER;?>">0%</span>
            </p>
            <div class="progress">
                <div class="progress-bar-<?= \Mageserv\Yamm\Model\Config\Source\CronType::CUSTOMER;?> progress-bar-sync">
                </div>
            </div>
        </div>

        <div id="progress-content-<?= \Mageserv\Yamm\Model\Config\Source\CronType::ORDER;?>" class="progress-content" style="display: none">
            <p class="text-right">
                <span id="syncing-<?= \Mageserv\Yamm\Model\Config\Source\CronType::ORDER;?>" class="syncing"><?= $block->escapeHtml(__('Syncing Orders...')) ?></span>
                <span id="sync-percent-<?= \Mageserv\Yamm\Model\Config\Source\CronType::ORDER;?>">0%</span>
            </p>
            <div class="progress">
                <div class="progress-bar-<?= \Mageserv\Yamm\Model\Config\Source\CronType::ORDER;?> progress-bar-sync">
                </div>
            </div>
        </div>

        <div id="progress-content-<?= \Mageserv\Yamm\Model\Config\Source\CronType::PRODUCT;?>" class="progress-content" style="display: none">
            <p class="text-right">
                <span id="syncing-<?= \Mageserv\Yamm\Model\Config\Source\CronType::PRODUCT;?>" class="syncing"><?= $block->escapeHtml(__('Syncing Products...')) ?></span>
                <span id="sync-percent-<?= \Mageserv\Yamm\Model\Config\Source\CronType::PRODUCT;?>">0%</span>
            </p>
            <div class="progress">
                <div class="progress-bar-<?= \Mageserv\Yamm\Model\Config\Source\CronType::PRODUCT;?> progress-bar-sync">
                </div>
            </div>
        </div>
        <div id="progress-content-<?= \Mageserv\Yamm\Model\Config\Source\CronType::CATEGORY;?>" class="progress-content" style="display: none">
            <p class="text-right">
                <span id="syncing-<?= \Mageserv\Yamm\Model\Config\Source\CronType::CATEGORY;?>" class="syncing"><?= $block->escapeHtml(__('Syncing Categories...')) ?></span>
                <span id="sync-percent-<?= \Mageserv\Yamm\Model\Config\Source\CronType::CATEGORY;?>">0%</span>
            </p>
            <div class="progress">
                <div class="progress-bar-<?= \Mageserv\Yamm\Model\Config\Source\CronType::CATEGORY;?> progress-bar-sync">
                </div>
            </div>
        </div>
        <div id="console-log" style="display: none">
            <textarea name="console-log" id="yamm-console-log" cols="30" rows="10" disabled></textarea>
            <input type="hidden" value="" id="yamm-log-data"
                   class="<?= /* @noEscape */ $block->getHtmlId() . '_console' ?>">
        </div>
        <div class="message" style="display: none;padding: 10px 10px 10px 48px;margin-bottom: 5px">
            <span class="message-text">
                <strong></strong>
            </span>
            <br>
        </div>
        <div class="multi-messages" style="display: none;padding: 10px 10px 10px 0;margin-bottom: 5px"></div>
    </div>
    <button class="actions-sync-order" type="button" id="<?= $block->getHtmlId() ?>">
        <span><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
<script type="text/x-magento-init">
    {
        "#<?= /* @noEscape */ $block->getElementId() ?>": {
            "<?= /* @noEscape */ $block->getComponent() ?>": {
                "ajaxUrl": "<?= $block->escapeHtml($block->getButtonUrl())?>",
                "estimateUrl": "<?= $block->escapeHtml($block->getEstimateUrl())?>",
                "successMessage": <?= /* @noEscape */ Data::jsonEncode($block->getSyncSuccessMessage())?>
    }
}
}
</script>
<style>
    .actions-log {
        margin-bottom: 25px;
    }

    .text-right {
        text-align: right;
    }

    .progress {
        background-color: #fafafa;
        border: 1px solid #ccc;
        clear: left;
        height: 30px;
        margin-bottom: 30px;
        overflow: hidden;
    }

    .progress-bar, .progress-bar-sync {
        background-color: #79a22e;
        color: #fff;
        float: left;
        height: 100%;
        text-align: center;
        width: 0;
        transition: width .6s ease;
    }
</style>
