<?php
$accountInfo = $block->getAccountInfo();
$pendingOrders = !empty($accountInfo['pending_request']) ? $accountInfo['pending_request']['total_orders'] : 0;
$statuses = !empty($accountInfo['pending_request']) && !empty($accountInfo['pending_request']['statuses']) ? $accountInfo['pending_request']['statuses'] : [];
$storeBalance = $accountInfo['store_balance'] ?? 0;
$storeCreditLimit = $accountInfo['store_limit'] ?? 0;
$RemainingStoreCreditLimit = $accountInfo['store_balance_with_credit'] ?? 0;
$storeCreditLimitUsage = $accountInfo['store_limit'] > 0 ? 100 * (1 - ($accountInfo['store_balance_with_credit'] / $accountInfo['store_limit'])) : 0;
?>
<div class="statistics-wrapper">
    <div class="flex-statistics-paper">
        <div class="d-flex">
            <p><?= __("Pending Orders"); ?></p>
            <div class="content-flex">
                <div class="tooltip_trigger" id="orders_tooltip_trigger" style="width: fit-content; display: flex; align-items: center;" aria-labelledby="orders_tooltip">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <rect width="24" height="24" rx="12" fill="#FFCD2E"></rect>
                        <path d="M12 12V8" stroke="white" stroke-width="1.5" stroke-linecap="round"
                              stroke-linejoin="round"></path>
                        <path
                            d="M12 21C16.9706 21 21 16.9706 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21Z"
                            stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                        <path
                            d="M12 16C12.2761 16 12.5 15.7761 12.5 15.5C12.5 15.2239 12.2761 15 12 15C11.7239 15 11.5 15.2239 11.5 15.5C11.5 15.7761 11.7239 16 12 16Z"
                            fill="white" stroke="white" stroke-linecap="round" stroke-linejoin="round"></path>
                    </svg>
                </div>
            </div>
        </div>
        <div class="d-flex">
            <div class="content-flex">
                <h1><?= $pendingOrders; ?></h1>
            </div>
        </div>
    </div>
    <div class="flex-statistics-paper">
        <div class="d-flex">
            <p><?= __("Store Balance"); ?></p>
            <div class="content-flex">
                <div class="tooltip_trigger" id="credit_tooltip_trigger"
                     style="width: fit-content; display: flex; align-items: center;"
                     aria-labelledby="credit_tooltip">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <rect width="24" height="24" rx="12" fill="#FFCD2E"></rect>
                        <path d="M12 12V8" stroke="white" stroke-width="1.5" stroke-linecap="round"
                              stroke-linejoin="round"></path>
                        <path
                            d="M12 21C16.9706 21 21 16.9706 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21Z"
                            stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                        <path
                            d="M12 16C12.2761 16 12.5 15.7761 12.5 15.5C12.5 15.2239 12.2761 15 12 15C11.7239 15 11.5 15.2239 11.5 15.5C11.5 15.7761 11.7239 16 12 16Z"
                            fill="white" stroke="white" stroke-linecap="round" stroke-linejoin="round"></path>
                    </svg>
                </div>
            </div>
        </div>
        <div class="d-flex">
            <div class="content-flex">
                <h1><?= $storeBalance; ?></h1>
                <p><?= __("SAR"); ?></p>
            </div>
        </div>
    </div>
</div>
<div role="tooltip"
     id="credit_tooltip"
     class="yamm_tooltip">
    <div class="MuiTooltip-tooltip"
         style="opacity: 1; transform: none; transition: opacity 200ms cubic-bezier(0.4, 0, 0.2, 1) 0ms, transform 133ms cubic-bezier(0.4, 0, 0.2, 1) 0ms;">
        <span>
            <div class="content-flex">
                <div class="flex-tooltip-title-wrapper">
                    <small><?= __("Remaining Store Credit"); ?></small>
                    <p><?= __("%1 SAR", $RemainingStoreCreditLimit); ?></p>
                </div>
                <div class="flex-tooltip-title-wrapper">
                    <small><?= __("Store Credit Limit"); ?></small>
                    <p><?= __("%1 SAR", $storeCreditLimit); ?></p>
                </div>
                <div class="flex-tooltip-title-wrapper">
                    <small><?= __("Credit Limit Usage"); ?></small>
                    <p><?= number_format($storeCreditLimitUsage, 2); ?>%</p>
                </div>
            </div>
        </span>
        <span class="MuiTooltip-arrow" data-popper-arrow></span>
    </div>
</div>
<div role="tooltip"
     id="orders_tooltip"
     class="yamm_tooltip">
    <div class="MuiTooltip-tooltip"
         style="opacity: 1; transform: none; transition: opacity 200ms cubic-bezier(0.4, 0, 0.2, 1) 0ms, transform 133ms cubic-bezier(0.4, 0, 0.2, 1) 0ms;">
        <span>
            <div class="content-flex">
                <?php foreach ($statuses as $status):?>
                    <div class="flex-tooltip-title-wrapper">
                        <small><?= $status['statusText'];?></small>
                        <p><?= $status['count'];?></p>
                    </div>
                <?php endforeach;?>
            </div>
        </span>
        <span class="MuiTooltip-arrow" data-popper-arrow></span></div>
</div>
<script type="text/javascript">
    require(['jquery', 'Mageserv_Yamm/js/popper.min'], function ($, Popper) {
        $('.tooltip_trigger').each(function () {
            let button = document.querySelector('#' + $(this).attr('id')),
                buttonLabel = this.getAttribute('aria-labelledby'),
                tooltip = document.querySelector('#' + buttonLabel);
            console.log(button);
            // Generate a unique name for popperInstance
            var popperInstanceName = 'popperInstance_' + buttonLabel.replace(/\W+/g, "_"); // Replace non-word characters with underscores

            // Check if the variable already exists, if not, create it
            if (typeof window[popperInstanceName] === 'undefined') {
                window[popperInstanceName] = Popper.createPopper(button, tooltip, {
                    placement: 'bottom',
                });
            }

            function show(popperInstance) {
                tooltip.setAttribute('data-show', '');
                popperInstance.setOptions((options) => ({
                    ...options,
                    modifiers: [
                        ...options.modifiers,
                        {name: 'eventListeners', enabled: true},
                    ],
                }));
                popperInstance.update();
            }

            function hide(popperInstance) {
                tooltip.removeAttribute('data-show');
                popperInstance.setOptions((options) => ({
                    ...options,
                    modifiers: [
                        ...options.modifiers,
                        {name: 'eventListeners', enabled: false},
                    ],
                }));
            }

            var showEvents = ['mouseenter', 'focus'],
                hideEvents = ['mouseleave', 'blur'];

            // Add event listeners for showEvents
            showEvents.forEach((event) => {
                button.addEventListener(event, () => {
                    show(window[popperInstanceName])
                });
            });

            hideEvents.forEach((event) => {
                button.addEventListener(event, () => {
                    hide(window[popperInstanceName])
                });
            });
        });
    });
</script>
